# syntax=docker/dockerfile:1

FROM apache/airflow:2.9.2-python3.12  

USER root  
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    postgresql-client  
    # Para pg_isready

USER airflow  
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt  
